import type { Category, Product } from "@/types";

export const categories: Category[] = [
  {
    id: "audio",
    name: "เสียงที่พอดีกับทุกวัน",
    shortName: "เครื่องเสียง",
    description: "หูฟังและลำโพงที่เลือกจากคุณภาพเสียง การใช้งาน และความสบาย",
    image: "/products/headphone_2.jpg",
  },
  {
    id: "home",
    name: "ของใช้ที่ทำให้บ้านเบาขึ้น",
    shortName: "บ้านและไลฟ์สไตล์",
    description: "อุปกรณ์ชิ้นเล็กที่ช่วยให้กิจวัตรประจำวันลื่นไหลกว่าเดิม",
    image: "/products/espresso.jpg",
  },
  {
    id: "travel",
    name: "ออกเดินทางอย่างเป็นระบบ",
    shortName: "ท่องเที่ยว",
    description: "สัมภาระและอุปกรณ์เดินทางที่เบา แข็งแรง และหยิบใช้สะดวก",
    image: "/products/luggage.jpg",
  },
  {
    id: "style",
    name: "รายละเอียดที่อยู่กับคุณ",
    shortName: "แฟชั่น",
    description: "รองเท้า นาฬิกา และของใช้ส่วนตัวที่เน้นวัสดุและสัดส่วน",
    image: "/products/sneakers.jpg",
  },
];

export const products: Product[] = [
  {
    id: "p-001",
    slug: "aerotone-headphones",
    name: "Aerotone หูฟังไร้สายตัดเสียงรบกวน",
    shortName: "Aerotone Headphones",
    description: "หูฟังครอบหูน้ำหนักเบา พร้อมโหมดตัดเสียงรบกวนและโหมดรับเสียงภายนอก เปลี่ยนจังหวะการฟังได้โดยไม่ต้องถอดหูฟัง",
    price: 2990,
    compareAtPrice: 3490,
    rating: 4.8,
    reviewCount: 328,
    soldCount: 1200,
    image: "/products/headphone_2.jpg",
    gallery: ["/products/headphone_2.jpg", "/products/headphones-alt.jpg"],
    categoryId: "audio",
    seller: "Northstar Audio",
    sellerRating: 4.9,
    delivery: "ถึงคุณภายใน 2–3 วัน",
    stock: 42,
    colors: [
      { name: "Cloud", value: "#E7E7E4" },
      { name: "Graphite", value: "#25272A" },
      { name: "Sky", value: "#9DB9D2" },
    ],
    specs: [
      { label: "แบตเตอรี่", value: "ใช้งานสูงสุด 36 ชั่วโมง" },
      { label: "น้ำหนัก", value: "248 กรัม" },
      { label: "การเชื่อมต่อ", value: "Bluetooth 5.3 / USB-C" },
    ],
    badge: "เลือกโดยทีม SKYMART",
  },
  {
    id: "p-002",
    slug: "morrow-espresso-mini",
    name: "Morrow เครื่องชงเอสเปรสโซขนาดกะทัดรัด",
    shortName: "Morrow Espresso Mini",
    description: "เครื่องชงกาแฟสำหรับพื้นที่จำกัด ควบคุมอุณหภูมิและแรงดันให้คงที่ พร้อมก้านสตีมนมที่ทำความสะอาดง่าย",
    price: 6990,
    rating: 4.7,
    reviewCount: 184,
    soldCount: 640,
    image: "/products/espresso.jpg",
    gallery: ["/products/espresso.jpg", "/products/espresso-alt.jpg"],
    categoryId: "home",
    seller: "Morrow Living",
    sellerRating: 4.8,
    delivery: "ถึงคุณภายใน 3–4 วัน",
    stock: 18,
    colors: [
      { name: "Steel", value: "#B9BAB8" },
      { name: "Ink", value: "#202225" },
    ],
    specs: [
      { label: "แรงดัน", value: "15 บาร์" },
      { label: "ความจุแทงก์", value: "1.2 ลิตร" },
      { label: "ขนาด", value: "18 × 32 × 30 ซม." },
    ],
  },
  {
    id: "p-003",
    slug: "atlas-carry-on",
    name: "Atlas กระเป๋าเดินทาง Carry-on",
    shortName: "Atlas Carry-on",
    description: "กระเป๋าขึ้นเครื่องโครงแข็งที่จัดพื้นที่ภายในเป็นสัดส่วน ล้อลื่น เงียบ และล็อก TSA ในตัว",
    price: 4290,
    rating: 4.9,
    reviewCount: 441,
    soldCount: 2100,
    image: "/products/luggage.jpg",
    gallery: ["/products/luggage.jpg", "/products/luggage-alt.jpg"],
    categoryId: "travel",
    seller: "Atlas Supply",
    sellerRating: 4.9,
    delivery: "ถึงคุณภายใน 2–3 วัน",
    stock: 31,
    colors: [
      { name: "Blue", value: "#2D6D9F" },
      { name: "Sand", value: "#C7BBA7" },
      { name: "Orange", value: "#DD683E" },
    ],
    specs: [
      { label: "ความจุ", value: "38 ลิตร" },
      { label: "น้ำหนัก", value: "3.1 กก." },
      { label: "ขนาด", value: "55 × 36 × 23 ซม." },
    ],
    badge: "พร้อมออกเดินทาง",
  },
  {
    id: "p-004",
    slug: "arc-desk-lamp",
    name: "Arc โคมไฟตั้งโต๊ะปรับอุณหภูมิสี",
    shortName: "Arc Desk Lamp",
    description: "แสงสำหรับโต๊ะทำงานที่ปรับทั้งความสว่างและอุณหภูมิสีได้ ฐานบางและแขนหมุนได้โดยไม่กินพื้นที่",
    price: 1890,
    rating: 4.6,
    reviewCount: 96,
    soldCount: 520,
    image: "/products/lamp.jpg",
    gallery: ["/products/lamp.jpg", "/products/lamp-alt.jpg"],
    categoryId: "home",
    seller: "Line & Light",
    sellerRating: 4.7,
    delivery: "ถึงคุณภายใน 2–4 วัน",
    stock: 55,
    colors: [
      { name: "Chalk", value: "#EEEDE8" },
      { name: "Charcoal", value: "#323438" },
    ],
    specs: [
      { label: "อุณหภูมิสี", value: "2700–5500K" },
      { label: "กำลังไฟ", value: "12 วัตต์" },
      { label: "การควบคุม", value: "สัมผัส / ตั้งเวลา" },
    ],
  },
  {
    id: "p-005",
    slug: "field-day-sneakers",
    name: "Field Day รองเท้าสนีกเกอร์น้ำหนักเบา",
    shortName: "Field Day Sneakers",
    description: "รองเท้าสำหรับเดินทั้งวัน โครงสร้างระบายอากาศและพื้นชั้นกลางที่รองรับแรงกระแทกโดยไม่หนาเทอะทะ",
    price: 2490,
    rating: 4.7,
    reviewCount: 267,
    soldCount: 980,
    image: "/products/sneakers.jpg",
    gallery: ["/products/sneakers.jpg", "/products/sneakers-alt.jpg"],
    categoryId: "style",
    seller: "Field Day Studio",
    sellerRating: 4.8,
    delivery: "ถึงคุณภายใน 2–3 วัน",
    stock: 64,
    colors: [
      { name: "Bone", value: "#DED9CF" },
      { name: "Signal", value: "#E66443" },
      { name: "Night", value: "#23262C" },
    ],
    specs: [
      { label: "วัสดุ", value: "ผ้าถักระบายอากาศ" },
      { label: "พื้นรองเท้า", value: "EVA สองความหนาแน่น" },
      { label: "ไซซ์", value: "EU 36–45" },
    ],
  },
  {
    id: "p-006",
    slug: "orbit-watch",
    name: "Orbit นาฬิกาสำหรับทุกวัน",
    shortName: "Orbit Everyday Watch",
    description: "นาฬิกาหน้าปัดอ่านง่าย ตัวเรือนสเตนเลส และสายที่เปลี่ยนได้โดยไม่ใช้เครื่องมือ",
    price: 3590,
    rating: 4.8,
    reviewCount: 142,
    soldCount: 430,
    image: "/products/watch.jpg",
    gallery: ["/products/watch.jpg", "/products/watch-alt.jpg"],
    categoryId: "style",
    seller: "Orbit Objects",
    sellerRating: 4.9,
    delivery: "ถึงคุณภายใน 3–4 วัน",
    stock: 22,
    colors: [
      { name: "Silver", value: "#B9BCC1" },
      { name: "Black", value: "#202225" },
    ],
    specs: [
      { label: "ตัวเรือน", value: "38 มม." },
      { label: "การกันน้ำ", value: "5 ATM" },
      { label: "กลไก", value: "Quartz ญี่ปุ่น" },
    ],
  },
];

export const featuredProducts = products.slice(0, 4);

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
